version: "3"
services:
  api:
    build: ./api
    command: npm run dev
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
    volumes:
      - ./api/src:/usr/src/app/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: websystem-docker-demo-frontend-dev
    command: npm start
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api

  nginx:
    image: nginx:1-alpine
    container_name: websystem-docker-demo-nginx-dev
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api

  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

volumes:
  mongodb_api:
